/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NearestRouteImport } from './routes/nearest'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsNameRouteImport } from './routes/collections_.$name'

const NearestRoute = NearestRouteImport.update({
  id: '/nearest',
  path: '/nearest',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsNameRoute = CollectionsNameRouteImport.update({
  id: '/collections_/$name',
  path: '/collections/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/nearest': typeof NearestRoute
  '/collections/$name': typeof CollectionsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/nearest': typeof NearestRoute
  '/collections/$name': typeof CollectionsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/nearest': typeof NearestRoute
  '/collections_/$name': typeof CollectionsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/collections' | '/nearest' | '/collections/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/collections' | '/nearest' | '/collections/$name'
  id: '__root__' | '/' | '/collections' | '/nearest' | '/collections_/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  NearestRoute: typeof NearestRoute
  CollectionsNameRoute: typeof CollectionsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nearest': {
      id: '/nearest'
      path: '/nearest'
      fullPath: '/nearest'
      preLoaderRoute: typeof NearestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections_/$name': {
      id: '/collections_/$name'
      path: '/collections/$name'
      fullPath: '/collections/$name'
      preLoaderRoute: typeof CollectionsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  NearestRoute: NearestRoute,
  CollectionsNameRoute: CollectionsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
