/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NearestRouteImport } from './routes/nearest'
import { Route as AllRouteImport } from './routes/all'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsNameEditRouteImport } from './routes/collections/$name.edit'

const NearestRoute = NearestRouteImport.update({
  id: '/nearest',
  path: '/nearest',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsNameEditRoute = CollectionsNameEditRouteImport.update({
  id: '/collections/$name/edit',
  path: '/collections/$name/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/nearest': typeof NearestRoute
  '/collections': typeof CollectionsIndexRoute
  '/collections/$name/edit': typeof CollectionsNameEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/nearest': typeof NearestRoute
  '/collections': typeof CollectionsIndexRoute
  '/collections/$name/edit': typeof CollectionsNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/nearest': typeof NearestRoute
  '/collections/': typeof CollectionsIndexRoute
  '/collections/$name/edit': typeof CollectionsNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all'
    | '/nearest'
    | '/collections'
    | '/collections/$name/edit'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all' | '/nearest' | '/collections' | '/collections/$name/edit'
  id:
    | '__root__'
    | '/'
    | '/all'
    | '/nearest'
    | '/collections/'
    | '/collections/$name/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRoute: typeof AllRoute
  NearestRoute: typeof NearestRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CollectionsNameEditRoute: typeof CollectionsNameEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nearest': {
      id: '/nearest'
      path: '/nearest'
      fullPath: '/nearest'
      preLoaderRoute: typeof NearestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$name/edit': {
      id: '/collections/$name/edit'
      path: '/collections/$name/edit'
      fullPath: '/collections/$name/edit'
      preLoaderRoute: typeof CollectionsNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRoute: AllRoute,
  NearestRoute: NearestRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CollectionsNameEditRoute: CollectionsNameEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
