/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NearestRouteImport } from './routes/nearest'
import { Route as AllRouteImport } from './routes/all'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsEditNameRouteImport } from './routes/collections/edit.$name'
import { Route as CollectionsImportNameFlossNamesRouteImport } from './routes/collections/import.$name.$flossNames'

const NearestRoute = NearestRouteImport.update({
  id: '/nearest',
  path: '/nearest',
  getParentRoute: () => rootRouteImport,
} as any)
const AllRoute = AllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsEditNameRoute = CollectionsEditNameRouteImport.update({
  id: '/collections/edit/$name',
  path: '/collections/edit/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsImportNameFlossNamesRoute =
  CollectionsImportNameFlossNamesRouteImport.update({
    id: '/collections/import/$name/$flossNames',
    path: '/collections/import/$name/$flossNames',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/nearest': typeof NearestRoute
  '/collections': typeof CollectionsIndexRoute
  '/collections/edit/$name': typeof CollectionsEditNameRoute
  '/collections/import/$name/$flossNames': typeof CollectionsImportNameFlossNamesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/nearest': typeof NearestRoute
  '/collections': typeof CollectionsIndexRoute
  '/collections/edit/$name': typeof CollectionsEditNameRoute
  '/collections/import/$name/$flossNames': typeof CollectionsImportNameFlossNamesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all': typeof AllRoute
  '/nearest': typeof NearestRoute
  '/collections/': typeof CollectionsIndexRoute
  '/collections/edit/$name': typeof CollectionsEditNameRoute
  '/collections/import/$name/$flossNames': typeof CollectionsImportNameFlossNamesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all'
    | '/nearest'
    | '/collections'
    | '/collections/edit/$name'
    | '/collections/import/$name/$flossNames'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all'
    | '/nearest'
    | '/collections'
    | '/collections/edit/$name'
    | '/collections/import/$name/$flossNames'
  id:
    | '__root__'
    | '/'
    | '/all'
    | '/nearest'
    | '/collections/'
    | '/collections/edit/$name'
    | '/collections/import/$name/$flossNames'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllRoute: typeof AllRoute
  NearestRoute: typeof NearestRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  CollectionsEditNameRoute: typeof CollectionsEditNameRoute
  CollectionsImportNameFlossNamesRoute: typeof CollectionsImportNameFlossNamesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nearest': {
      id: '/nearest'
      path: '/nearest'
      fullPath: '/nearest'
      preLoaderRoute: typeof NearestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all': {
      id: '/all'
      path: '/all'
      fullPath: '/all'
      preLoaderRoute: typeof AllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/edit/$name': {
      id: '/collections/edit/$name'
      path: '/collections/edit/$name'
      fullPath: '/collections/edit/$name'
      preLoaderRoute: typeof CollectionsEditNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/import/$name/$flossNames': {
      id: '/collections/import/$name/$flossNames'
      path: '/collections/import/$name/$flossNames'
      fullPath: '/collections/import/$name/$flossNames'
      preLoaderRoute: typeof CollectionsImportNameFlossNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllRoute: AllRoute,
  NearestRoute: NearestRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  CollectionsEditNameRoute: CollectionsEditNameRoute,
  CollectionsImportNameFlossNamesRoute: CollectionsImportNameFlossNamesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
